CREATE OR REPLACE FUNCTION obter_descricao_venda
(p_VENDA_ID IN VENDA.ID_VENDA%type)
RETURN VENDA.DESCRICAO%type

IS
v_DESCRICAO VENDA.DESCRICAO%type;

BEGIN

SELECT DESCRICAO INTO v_DESCRICAO FROM VENDA WHERE ID_VENDA=p_VENDA_ID;
RETURN v_DESCRICAO;

END;
