CREATE OR REPLACE PROCEDURE incluir_registro
(p_ID_VENDA IN VENDA.ID_VENDA%type, p_QUANTIDADE IN VENDA.QUANTIDADE%type, p_DESCRICAO IN VENDA.DESCRICAO%type) 

IS

BEGIN

INSERT INTO venda (ID_VENDA, QUANTIDADE, DESCRICAO) VALUES (p_ID_VENDA, p_QUANTIDADE, p_DESCRICAO);
COMMIT;
END;
